# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.26.3/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.26.3/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/ronjajohannsdottir/Documents/Skóli/Freestyle/Game

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/ronjajohannsdottir/Documents/Skóli/Freestyle/Game

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.26.3/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.26.3/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/ronjajohannsdottir/Documents/Skóli/Freestyle/Game/CMakeFiles /Users/ronjajohannsdottir/Documents/Skóli/Freestyle/Game//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/ronjajohannsdottir/Documents/Skóli/Freestyle/Game/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named GameEngine

# Build rule for target.
GameEngine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GameEngine
.PHONY : GameEngine

# fast build rule for target.
GameEngine/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/build
.PHONY : GameEngine/fast

src/core/Game.o: src/core/Game.cpp.o
.PHONY : src/core/Game.o

# target to build an object file
src/core/Game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/core/Game.cpp.o
.PHONY : src/core/Game.cpp.o

src/core/Game.i: src/core/Game.cpp.i
.PHONY : src/core/Game.i

# target to preprocess a source file
src/core/Game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/core/Game.cpp.i
.PHONY : src/core/Game.cpp.i

src/core/Game.s: src/core/Game.cpp.s
.PHONY : src/core/Game.s

# target to generate assembly for a file
src/core/Game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/core/Game.cpp.s
.PHONY : src/core/Game.cpp.s

src/core/engine.o: src/core/engine.cpp.o
.PHONY : src/core/engine.o

# target to build an object file
src/core/engine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/core/engine.cpp.o
.PHONY : src/core/engine.cpp.o

src/core/engine.i: src/core/engine.cpp.i
.PHONY : src/core/engine.i

# target to preprocess a source file
src/core/engine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/core/engine.cpp.i
.PHONY : src/core/engine.cpp.i

src/core/engine.s: src/core/engine.cpp.s
.PHONY : src/core/engine.s

# target to generate assembly for a file
src/core/engine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/core/engine.cpp.s
.PHONY : src/core/engine.cpp.s

src/glad.o: src/glad.c.o
.PHONY : src/glad.o

# target to build an object file
src/glad.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/glad.c.o
.PHONY : src/glad.c.o

src/glad.i: src/glad.c.i
.PHONY : src/glad.i

# target to preprocess a source file
src/glad.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/glad.c.i
.PHONY : src/glad.c.i

src/glad.s: src/glad.c.s
.PHONY : src/glad.s

# target to generate assembly for a file
src/glad.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/glad.c.s
.PHONY : src/glad.c.s

src/graphics/materials/Material.o: src/graphics/materials/Material.cpp.o
.PHONY : src/graphics/materials/Material.o

# target to build an object file
src/graphics/materials/Material.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/graphics/materials/Material.cpp.o
.PHONY : src/graphics/materials/Material.cpp.o

src/graphics/materials/Material.i: src/graphics/materials/Material.cpp.i
.PHONY : src/graphics/materials/Material.i

# target to preprocess a source file
src/graphics/materials/Material.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/graphics/materials/Material.cpp.i
.PHONY : src/graphics/materials/Material.cpp.i

src/graphics/materials/Material.s: src/graphics/materials/Material.cpp.s
.PHONY : src/graphics/materials/Material.s

# target to generate assembly for a file
src/graphics/materials/Material.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/graphics/materials/Material.cpp.s
.PHONY : src/graphics/materials/Material.cpp.s

src/graphics/rendering/Renderer.o: src/graphics/rendering/Renderer.cpp.o
.PHONY : src/graphics/rendering/Renderer.o

# target to build an object file
src/graphics/rendering/Renderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/graphics/rendering/Renderer.cpp.o
.PHONY : src/graphics/rendering/Renderer.cpp.o

src/graphics/rendering/Renderer.i: src/graphics/rendering/Renderer.cpp.i
.PHONY : src/graphics/rendering/Renderer.i

# target to preprocess a source file
src/graphics/rendering/Renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/graphics/rendering/Renderer.cpp.i
.PHONY : src/graphics/rendering/Renderer.cpp.i

src/graphics/rendering/Renderer.s: src/graphics/rendering/Renderer.cpp.s
.PHONY : src/graphics/rendering/Renderer.s

# target to generate assembly for a file
src/graphics/rendering/Renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/graphics/rendering/Renderer.cpp.s
.PHONY : src/graphics/rendering/Renderer.cpp.s

src/graphics/shaders/ShaderProgram.o: src/graphics/shaders/ShaderProgram.cpp.o
.PHONY : src/graphics/shaders/ShaderProgram.o

# target to build an object file
src/graphics/shaders/ShaderProgram.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/graphics/shaders/ShaderProgram.cpp.o
.PHONY : src/graphics/shaders/ShaderProgram.cpp.o

src/graphics/shaders/ShaderProgram.i: src/graphics/shaders/ShaderProgram.cpp.i
.PHONY : src/graphics/shaders/ShaderProgram.i

# target to preprocess a source file
src/graphics/shaders/ShaderProgram.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/graphics/shaders/ShaderProgram.cpp.i
.PHONY : src/graphics/shaders/ShaderProgram.cpp.i

src/graphics/shaders/ShaderProgram.s: src/graphics/shaders/ShaderProgram.cpp.s
.PHONY : src/graphics/shaders/ShaderProgram.s

# target to generate assembly for a file
src/graphics/shaders/ShaderProgram.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/graphics/shaders/ShaderProgram.cpp.s
.PHONY : src/graphics/shaders/ShaderProgram.cpp.s

src/input/InputManager.o: src/input/InputManager.cpp.o
.PHONY : src/input/InputManager.o

# target to build an object file
src/input/InputManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/input/InputManager.cpp.o
.PHONY : src/input/InputManager.cpp.o

src/input/InputManager.i: src/input/InputManager.cpp.i
.PHONY : src/input/InputManager.i

# target to preprocess a source file
src/input/InputManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/input/InputManager.cpp.i
.PHONY : src/input/InputManager.cpp.i

src/input/InputManager.s: src/input/InputManager.cpp.s
.PHONY : src/input/InputManager.s

# target to generate assembly for a file
src/input/InputManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/input/InputManager.cpp.s
.PHONY : src/input/InputManager.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/math_utils/math_utils.o: src/math_utils/math_utils.cpp.o
.PHONY : src/math_utils/math_utils.o

# target to build an object file
src/math_utils/math_utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/math_utils/math_utils.cpp.o
.PHONY : src/math_utils/math_utils.cpp.o

src/math_utils/math_utils.i: src/math_utils/math_utils.cpp.i
.PHONY : src/math_utils/math_utils.i

# target to preprocess a source file
src/math_utils/math_utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/math_utils/math_utils.cpp.i
.PHONY : src/math_utils/math_utils.cpp.i

src/math_utils/math_utils.s: src/math_utils/math_utils.cpp.s
.PHONY : src/math_utils/math_utils.s

# target to generate assembly for a file
src/math_utils/math_utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/math_utils/math_utils.cpp.s
.PHONY : src/math_utils/math_utils.cpp.s

src/scene/camera/Camera.o: src/scene/camera/Camera.cpp.o
.PHONY : src/scene/camera/Camera.o

# target to build an object file
src/scene/camera/Camera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/scene/camera/Camera.cpp.o
.PHONY : src/scene/camera/Camera.cpp.o

src/scene/camera/Camera.i: src/scene/camera/Camera.cpp.i
.PHONY : src/scene/camera/Camera.i

# target to preprocess a source file
src/scene/camera/Camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/scene/camera/Camera.cpp.i
.PHONY : src/scene/camera/Camera.cpp.i

src/scene/camera/Camera.s: src/scene/camera/Camera.cpp.s
.PHONY : src/scene/camera/Camera.s

# target to generate assembly for a file
src/scene/camera/Camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/scene/camera/Camera.cpp.s
.PHONY : src/scene/camera/Camera.cpp.s

src/scene/collision/Collision.o: src/scene/collision/Collision.cpp.o
.PHONY : src/scene/collision/Collision.o

# target to build an object file
src/scene/collision/Collision.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/scene/collision/Collision.cpp.o
.PHONY : src/scene/collision/Collision.cpp.o

src/scene/collision/Collision.i: src/scene/collision/Collision.cpp.i
.PHONY : src/scene/collision/Collision.i

# target to preprocess a source file
src/scene/collision/Collision.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/scene/collision/Collision.cpp.i
.PHONY : src/scene/collision/Collision.cpp.i

src/scene/collision/Collision.s: src/scene/collision/Collision.cpp.s
.PHONY : src/scene/collision/Collision.s

# target to generate assembly for a file
src/scene/collision/Collision.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/scene/collision/Collision.cpp.s
.PHONY : src/scene/collision/Collision.cpp.s

src/scene/lighting/Lighting.o: src/scene/lighting/Lighting.cpp.o
.PHONY : src/scene/lighting/Lighting.o

# target to build an object file
src/scene/lighting/Lighting.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/scene/lighting/Lighting.cpp.o
.PHONY : src/scene/lighting/Lighting.cpp.o

src/scene/lighting/Lighting.i: src/scene/lighting/Lighting.cpp.i
.PHONY : src/scene/lighting/Lighting.i

# target to preprocess a source file
src/scene/lighting/Lighting.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/scene/lighting/Lighting.cpp.i
.PHONY : src/scene/lighting/Lighting.cpp.i

src/scene/lighting/Lighting.s: src/scene/lighting/Lighting.cpp.s
.PHONY : src/scene/lighting/Lighting.s

# target to generate assembly for a file
src/scene/lighting/Lighting.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/scene/lighting/Lighting.cpp.s
.PHONY : src/scene/lighting/Lighting.cpp.s

src/scene/manager/SceneManager.o: src/scene/manager/SceneManager.cpp.o
.PHONY : src/scene/manager/SceneManager.o

# target to build an object file
src/scene/manager/SceneManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/scene/manager/SceneManager.cpp.o
.PHONY : src/scene/manager/SceneManager.cpp.o

src/scene/manager/SceneManager.i: src/scene/manager/SceneManager.cpp.i
.PHONY : src/scene/manager/SceneManager.i

# target to preprocess a source file
src/scene/manager/SceneManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/scene/manager/SceneManager.cpp.i
.PHONY : src/scene/manager/SceneManager.cpp.i

src/scene/manager/SceneManager.s: src/scene/manager/SceneManager.cpp.s
.PHONY : src/scene/manager/SceneManager.s

# target to generate assembly for a file
src/scene/manager/SceneManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/scene/manager/SceneManager.cpp.s
.PHONY : src/scene/manager/SceneManager.cpp.s

src/scene/object/GameObject.o: src/scene/object/GameObject.cpp.o
.PHONY : src/scene/object/GameObject.o

# target to build an object file
src/scene/object/GameObject.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/scene/object/GameObject.cpp.o
.PHONY : src/scene/object/GameObject.cpp.o

src/scene/object/GameObject.i: src/scene/object/GameObject.cpp.i
.PHONY : src/scene/object/GameObject.i

# target to preprocess a source file
src/scene/object/GameObject.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/scene/object/GameObject.cpp.i
.PHONY : src/scene/object/GameObject.cpp.i

src/scene/object/GameObject.s: src/scene/object/GameObject.cpp.s
.PHONY : src/scene/object/GameObject.s

# target to generate assembly for a file
src/scene/object/GameObject.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/scene/object/GameObject.cpp.s
.PHONY : src/scene/object/GameObject.cpp.s

src/utilities/Utilities.o: src/utilities/Utilities.cpp.o
.PHONY : src/utilities/Utilities.o

# target to build an object file
src/utilities/Utilities.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/utilities/Utilities.cpp.o
.PHONY : src/utilities/Utilities.cpp.o

src/utilities/Utilities.i: src/utilities/Utilities.cpp.i
.PHONY : src/utilities/Utilities.i

# target to preprocess a source file
src/utilities/Utilities.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/utilities/Utilities.cpp.i
.PHONY : src/utilities/Utilities.cpp.i

src/utilities/Utilities.s: src/utilities/Utilities.cpp.s
.PHONY : src/utilities/Utilities.s

# target to generate assembly for a file
src/utilities/Utilities.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/utilities/Utilities.cpp.s
.PHONY : src/utilities/Utilities.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... GameEngine"
	@echo "... src/core/Game.o"
	@echo "... src/core/Game.i"
	@echo "... src/core/Game.s"
	@echo "... src/core/engine.o"
	@echo "... src/core/engine.i"
	@echo "... src/core/engine.s"
	@echo "... src/glad.o"
	@echo "... src/glad.i"
	@echo "... src/glad.s"
	@echo "... src/graphics/materials/Material.o"
	@echo "... src/graphics/materials/Material.i"
	@echo "... src/graphics/materials/Material.s"
	@echo "... src/graphics/rendering/Renderer.o"
	@echo "... src/graphics/rendering/Renderer.i"
	@echo "... src/graphics/rendering/Renderer.s"
	@echo "... src/graphics/shaders/ShaderProgram.o"
	@echo "... src/graphics/shaders/ShaderProgram.i"
	@echo "... src/graphics/shaders/ShaderProgram.s"
	@echo "... src/input/InputManager.o"
	@echo "... src/input/InputManager.i"
	@echo "... src/input/InputManager.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/math_utils/math_utils.o"
	@echo "... src/math_utils/math_utils.i"
	@echo "... src/math_utils/math_utils.s"
	@echo "... src/scene/camera/Camera.o"
	@echo "... src/scene/camera/Camera.i"
	@echo "... src/scene/camera/Camera.s"
	@echo "... src/scene/collision/Collision.o"
	@echo "... src/scene/collision/Collision.i"
	@echo "... src/scene/collision/Collision.s"
	@echo "... src/scene/lighting/Lighting.o"
	@echo "... src/scene/lighting/Lighting.i"
	@echo "... src/scene/lighting/Lighting.s"
	@echo "... src/scene/manager/SceneManager.o"
	@echo "... src/scene/manager/SceneManager.i"
	@echo "... src/scene/manager/SceneManager.s"
	@echo "... src/scene/object/GameObject.o"
	@echo "... src/scene/object/GameObject.i"
	@echo "... src/scene/object/GameObject.s"
	@echo "... src/utilities/Utilities.o"
	@echo "... src/utilities/Utilities.i"
	@echo "... src/utilities/Utilities.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

